### ISSUE TITLE
Reliance on debug_assert! for memory safety

### ISSUE THREAD

**Issue by niklasf** [sundy-li/partial_sort#7]
Hi, thanks for super useful crate!

There's a minor soundness issue with

https://github.com/sundy-li/partial_sort/blob/ed9ca021a44693c6ab6ba09b9f62e019d9bc88c5/src/lib.rs#L124

being protected by only

https://github.com/sundy-li/partial_sort/blob/ed9ca021a44693c6ab6ba09b9f62e019d9bc88c5/src/lib.rs#L58

Since debug assertions are disabled in release mode, they cannot be relied upon for memory safety. So for example

```rust
let mut buf = [2, 1];
buf.partial_sort(3, |a, b| a.cmp(b));
```

would trigger an out of bounds read when compiled with `--release` or with `RUSTFLAGS="-C debug-assertions=no"`.

**Comment by sundy-li** [comment]
Thanks for the report, I think it's ok to change it to `assert`.
